

services:
  nginx:
    image: nginx:1.31.5
    container_name: owl-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - ./logs:/var/log/nginx
      - ./html:/usr/share/nginx/html
    restart: always
