

services:
  redis6:
    image: redis:7.4.6
    container_name: redis-alone
    restart: always 
    ports:
      - "6379:6379"  
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
        
