

services:
  mysql:
    image: mysql:8.0.20
    container_name: owl_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456qin
    volumes:
      - ./data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - ./logs:/var/log/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root","-p123456qin"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1500M
        reservations:
          cpus: '0.5'
          memory: 500M

