

services:
  rabbitmq:
    image: rabbitmq:4.1.5-management
    container_name: owl-rabbitmq
    restart: always
    ports:
      - "5672:5672"      # AMQP协议端口
      - "15672:15672"    # 管理后台端口
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456qin
      TZ: Asia/Shanghai
    volumes:
      - ./data:/var/lib/rabbitmq:rw
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

